### ISSUE TITLE
Pro version ID Managment

### ISSUE THREAD

**Issue by merhovon** [croccio/CarTube#19]
Hello @croccio,

I was checking out the application in my car and when I went to log in to Youtube the application crashed.
After restarting the application I could not use the Pro version because the application suddenly had a new ID. 

The assignment of the unique ID should be redesigned. I would also have a problem with the ID when I get a new cell phone in a year through my mobile contract, so I would have a new ID and could no longer use the application. Therefore, the ID should best be replaced by an e-mail or an account, so I would also have no problems with new devices and also in case of a program error would not have to wait until the application is released by you again.

**Comment by croccio** [comment]
If ur id has changed send me the new one and I'll replace it. I have to do a login system, but then we have two level of login:
- App level login
- YouTUbe level login

it is confusing.

The UID changes also if u buy the new phone! 

I have to think about this, if I find nothing else, then i'm going to implement a login system
