### ISSUE TITLE
Voice search doesn't work properly

### ISSUE THREAD

**Issue by croccio** [croccio/CarTube#2]
I took a short drive and the voice search animation appears andimmediately disappears and shows "no results".

by HofaTheRipper

**Comment by HofaTheRipper** [comment]
Found the problem for voice search: The permission of CarTube for the microphone was not set. I set it manually and voila... works like a charme! You should set this permission with your installer... maybe Android 11 is different because of the new permission system?

**Comment by croccio** [comment]
Permission is requested when you open app for the first time. However great idea set permission by installer :D I've not Androdi 11 :( i'm stuck on android 10 (and another device with android 8.1 :( )
