### ISSUE TITLE
Ads showing on Pro

### ISSUE THREAD

**Issue by princepeace** [croccio/CarTube#25]
On the Pro, Ads still show before some videos.

**Comment by Raperowy** [comment]
let us login and use our YouTube Premium Plan

**Comment by croccio** [comment]
Tomorrow i'm going to release new version with working login

Il sab 27 mar 2021, 19:29 Raperowy ***@***.***> ha scritto:

**Comment by princepeace** [comment]
Ads don't seem to be coming through anymore
