### ISSUE TITLE
applicazione windows si blocca

### ISSUE THREAD

**Issue by AlessandroLeone** [croccio/CarTube#28]
Avvio il programma e arrivo al punto 3, parte un icona di caricamento, cosi seguo le istruzioni che si leggono nello sfondo mentre questa icona continua a girare.
Attivo il Debug USB, clicco OK sul messaggio "consentire debug usb".
(non mi compare nessun "Allow always from this computer")
Ma l'icona di caricamento nel programma continua a girare non permettendomi di cliccare niente, ma solo di chiudere il programma.

**Comment by croccio** [comment]
Puoi allegare uno screenshot? che telefono hai?

Il giorno sab 27 mar 2021 alle ore 10:37 AlessandroLeone <
***@***.***> ha scritto:

**Comment by AlessandroLeone** [comment]
ok ho riavviato il telefono ed è partito, funziona tutto, scusa.
