### ISSUE TITLE
Control playback via the steering wheel

### ISSUE THREAD

**Issue by merhovon** [croccio/CarTube#31]
With the Spotify APP and YouTube APP I can control the playback with the buttons on the steering wheel that should also go with the app.

With Spotify, here's what I can do:

- Pause playback 
- Play next track
- Play previous track

**Comment by costa802** [comment]
With cartube also

**Comment by croccio** [comment]
Are you using CarTube controller too?

Il sab 27 mar 2021, 20:09 merhovon ***@***.***> ha scritto:

**Comment by merhovon** [comment]
Yes I have both APPs installed.

**Comment by merhovon** [comment]
With the beta version it now works again in my Skoda.
