### ISSUE TITLE
Error downloading apk

### ISSUE THREAD

**Issue by Maggot20** [croccio/CarTube#51]
Ciao e grazie per la bella app!

Purtroppo non mi conclude l'installazione perchè compare il messaggio: 

error downloading cartTube.apk

premetto che sul cellulare non mi compare nulla, samsung s10 5g

Cosa posso fare?

grazie in anticipo

![Capture](https://user-images.githubusercontent.com/82053575/113755971-31c27d80-9711-11eb-9b19-b0b33a16480e.JPG)

**Comment by Brndiar1** [comment]
Try install files here https://drive.google.com/drive/folders/1i2NFp-5ZRgz5VKpgz3DB7DbqV9h8y5qg?usp=sharing
Helps me lot.
