### ISSUE TITLE
Error down

### ISSUE THREAD

**Issue by Maxmilian1** [croccio/CarTube#53]
Hi, Croccio
I tried with 2 computers with Windows 10, first with my huawei p30lite phone and then with my friend's xiaomi, it recognizes the phones asks for debug authorization, ok, it comes to the end and does not install: cartube.apk download error.  
can you help me?  
P.s. Where is the donation link?

**Comment by croccio** [comment]
pls write me on my email cwz.scardigno@gmail.com
