### ISSUE TITLE
Installation issue sdk version

### ISSUE THREAD

**Issue by ihackurmind** [croccio/CarTube#54]
Hello, 
I tried to install the app on Hauwei VIE-L09 (Android 7.0) by using both beta version of _general_ and _windows_ installation. 

In both cases, the procedure stopped and the installer shows this message. 

I guess my phone's android version is not able to support the app. 

Any help? Thanks

![image](https://user-images.githubusercontent.com/25226744/113840370-e5b71d80-9790-11eb-8abb-6c2030815633.png)

**Comment by croccio** [comment]
app is for android 8 and major
